name: PRBuilder

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build V0.1.0
        uses: docker/build-push-action@v2
        with:
          context: podtato-server
          file: ./docker/DockerfileV0.1.0
          push: false
          tags: podtatoserver:v0.1.0
      - name: Build V0.1.1
        uses: docker/build-push-action@v2
        with:
          context: podtato-server
          file: ./docker/DockerfileV0.1.1
          push: false
          tags: podtatoserver:v0.1.1
      - name: Build V0.1.2
        uses: docker/build-push-action@v2
        with:
          context: podtato-server
          file: ./docker/DockerfileV0.1.2
          push: false
          tags: podtatoserver:v0.1.2
