name: PRBuilder

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:

defaults:
  run:
    working-directory: ./podtato-server
jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
        # Setup Complete of local registry for testing
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # Completed cache setup
      - name: Build V0.1.0
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/DockerfileV0.1.0
          push: false
          tags: podtatoserver:v0.1.0
      - name: Build V0.1.1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/DockerfileV0.1.1
          push: false
          tags: podtatoserver:v0.1.1
      - name: Build V0.1.2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/DockerfileV0.1.2
          push: false
          tags: podtatoserver:v0.1.2
